# Generated by Django 5.0.1 on 2024-01-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_visit_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
