# Generated by Django 5.0.1 on 2024-01-18 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_visit_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='type_of_cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cuisine', to='api.typeofcuisine'),
        ),
    ]
